#This is the basic workflow to help you get started Actions
name: CI

#Controls when the action will run
on:
#Trigger the workflow on push or pull request events but only for the master branch
push:
branches: [main]
pull_request:
branches: [main]

#Allows you to run tabs workflow manually from the Action tab
workflow_dispatch:

#A workflow run is made up of of one or more jobs that can run sequentially on in parallel
jobs:
#This workflow contais a single job called "build"
build:
#The type of runner that the job will run on
run-on: ubuntu-lates

#Steps represent a sequence of task that will be executed as part of the job
steps:
  #CHeck-out your repository under $GITHU_WORKSPACE, so your job can access it
  - uses: actions/checkout@v2

  #Runs a single command using the runners shell
  - name: Run a one-line script
run: echo Hello, world!
  
  #Runs a set of commands using the runners shell
  - name: Run a multi-line script
    run: |
    echo Add ither actions to build
    echo test, and deploy your project.

